name: Build

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm
      
      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Client
        run: npm run action src/electron/package_linux
      
      - name: Upload Linux Client
        uses: actions/upload-artifact@v2
        with:
          name: unsigned-linux-client
          path: build/dist/Outline-Client.AppImage

  windows:
    name: Windows
    runs-on: windows-2019
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Windows Client
        run: npm run action src/electron/package_windows

      - name: Upload Windows Client
        uses: actions/upload-artifact@v2
        with:
          name: unsigned-windows-client
          path: build/dist/Outline-Client.exe

  mac:
    name: MacOS
    runs-on: macos-11
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Set XCode Version
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app

      - name: Build OSX Client
        run: npx gulp build --platform=osx

      - name: Upload OSX Client
        uses: actions/upload-artifact@v2
        with:
          name: unsigned-osx-client
          path: platforms/osx/build/Outline.app

  ios:
    name: iOS
    runs-on: macos-11
    timeout-minutes: 10
    env:
      MATCH_GIT_BASIC_AUTHORIZATION: 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Set XCode Version
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      
      - name: Set Auth
        run: echo "MATCH_GIT_BASIC_AUTHORIZATION=$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64)" >> $GITHUB_ENV

      - name: Auth Test
        run: |
          echo ${{ github.actor }}
          echo $MATCH_GIT_BASIC_AUTHORIZATION

      - name: Build iOS Client
        run: npm run action apple/scripts/ios_package_remote

  android:
    name: Android
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup Android
        run: bash ./tools/build/setup_linux_android.sh

      - name: Build Android Client
        run: npx gulp build --platform=android

      - name: Upload Android Client
        uses: actions/upload-artifact@v2
        with:
          name: unsigned-android-client
          path: platforms/android/app/build/outputs/apk
